name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行
    paths:
      - 'backend/**'  # バックエンドディレクトリの変更時のみ実行

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and deploy to Cloud Run
        run: |
          cd backend
          gcloud run deploy mbti-diary-backend \
            --source . \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}"
      
      - name: Show deployed service URL
        run: |
          echo "Backend deployed to: $(gcloud run services describe mbti-diary-backend --region asia-northeast1 --format='value(status.url)')"