name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行
    paths:
      - 'backend/**'  # バックエンドディレクトリの変更時のみ実行

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      
      - name: Build and deploy to Cloud Run
        run: |
          cd backend
          gcloud run deploy mbti-diary-backend \
            --source . \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}"
      
      - name: Show deployed service URL
        run: |
          echo "Backend deployed to: $(gcloud run services describe mbti-diary-backend --region asia-northeast1 --format='value(status.url)')"