name: Deploy Frontend to App Engine

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行
    paths:
      - 'app/**'
      - 'components/**'
      - 'constants/**'
      - 'hooks/**'
      - 'services/**'
      - 'types/**'
      - 'assets/**'
      - 'package.json'
      - 'app.json'
      - 'app.config.js'
      - 'app.yaml'
      - '!backend/**'  # バックエンドのファイルは除外

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build:web
        env:
          EXPO_PUBLIC_API_URL: ${{ secrets.BACKEND_API_URL }}
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
      
      - name: Show deployed app URL
        run: |
          echo "Frontend deployed to: $(gcloud app describe --format='value(defaultHostname)')"