name: Full Stack Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/full-deploy.yml'  # 手動トリガーまたはこのファイル自体が更新された場合
  workflow_dispatch:  # 手動実行のためのトリガー

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      
      - name: Build and deploy to Cloud Run
        run: |
          cd backend
          gcloud run deploy mbti-diary-backend \
            --source . \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}"
      
      - name: Show deployed service URL
        id: backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe mbti-diary-backend --region asia-northeast1 --format='value(status.url)')
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
          echo "Backend deployed to: $BACKEND_URL"
  
  deploy-frontend:
    name: Deploy Frontend
    needs: deploy-backend  # バックエンドデプロイ後に実行
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build:web
        env:
          EXPO_PUBLIC_API_URL: ${{ env.BACKEND_URL }}/api/v1
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
      
      - name: Show deployed app URL
        run: |
          echo "Frontend deployed to: https://$(gcloud app describe --format='value(defaultHostname)')"
          
  notify-deployment:
    name: Notify Deployment Completion
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    
    steps:
      - name: Send deployment notification
        run: |
          echo "✅ 完全デプロイが完了しました！"
          echo "バックエンド: ${{ env.BACKEND_URL }}"
          echo "フロントエンド: https://$(gcloud app describe --format='value(defaultHostname)')"